config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#front'
  resources :pages, only: [:index]

  resources :questions, only: [:index, :show, :create, :destroy], param: :slug do
    resources :answers, only: [:create, :destroy] do
      member do
        post 'vote'
      end
    end
    collection do
      get 'interest'
    end
  end

  resources :searches, only: [:index]

  resources :users, only: [:create, :edit, :show, :update]

  get 'register', to: 'users#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notifications
  has_many :answers
  has_many :questions
  has_many :votes

  has_secure_password validations: false

  has_many :user_topics
  has_many :topics, through: :user_topics

  validates :email, presence: true
  validates :email, uniqueness: {message: "email must be unique."}
  validates :password, length: {minimum: 5, message: "password must be mimimum of 5 characters"}
  validates :name, presence: true

  validate :password_alphanumeric

  def admin?
    self.position == 'admin'
  end

  def password_alphanumeric
    unless password =~ /[a-zA-Z]/ && password =~ /[0-9]/
      errors.add(:password, "password must contain both letters and numbers")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "User successfully registered."
      redirect_to root_path
    else
      flash[:warning] = @user.errors.full_messages.first
      render :new
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User profile successfully updated"
      redirect_to user_path(@user)
    else
      flash[:warning] = @user.errors.full_messages.first
      render :edit
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :location, :description, :work, topic_ids: [])
  end
end

app/views/users/edit.html.haml
.container.p-3
  .row
    .col-3
    .col-6
      %h5 Account Settings
      %hr/
      = form_for @user do |f|
        .form-group.row
          = f.label :name, 'Your Name', class: 'col-3 col-form-label'
          .col-9
            = f.text_field :name, class: 'form-control'
        .form-group.row
          = f.label :email, 'Email Address', class: 'col-3 col-form-label'
          .col-9
            = f.email_field :email, class: 'form-control', placeholder: 'email@example.com'
        .form-group.row
          = f.label :password, 'Password', class: 'col-3 col-form-label'
          .col-9
            = f.password_field :password, class: 'form-control', placeholder: 'enter password'
        .form-group.row
          = f.label :location, 'Location (optional)', class: 'col-3 col-form-label'
          .col-9
            = f.text_field :location, class: 'form-control'
        .form-group.row
          = f.label :description, 'Description (optional)', class: 'col-3 col-form-label'
          .col-9
            = f.text_area :description, class: 'form-control', placeholder: 'Describe Yourself', rows: '3'
        .form-group.row
          = f.label :work, "Occupation (optional)", class: 'col-3 col-form-label'
          .col-9
            = f.text_field :work, class: 'form-control', placeholder: 'Your job'
        .form-group.row
          .col-3 Topics Interested (optional)
          .col-9
            = f.collection_check_boxes(:topic_ids, Topic.all, :id, :name) do |cb|
              .form-check
                = cb.label(class: 'form-check-label') { cb.check_box(class: 'form-check-input') + cb.text}
        .form-group.row
          .col-3
          .col-9
            = f.submit "Update Profile", class: 'btn btn-primary'
            

app/views/users/new.html.haml
.container.p-3
  .row
    .col-3

    .col-6
      %h5 Register Account
      %hr/
      = form_for @user do |f|
        .form-group.row
          = f.label :name, 'Your Name', class: 'col-3 col-form-label'
          .col-9
            = f.text_field :name, class: 'form-control'
        .form-group.row
          = f.label :email, 'Email Address', class: 'col-3 col-form-label'
          .col-9
            = f.email_field :email, class: 'form-control', placeholder: 'email@example.com'
        .form-group.row
          = f.label :password, 'Password', class: 'col-3 col-form-label'
          .col-9
            = f.password_field :password, class: 'form-control', placeholder: 'enter password'
        .form-group.row
          = f.label :location, 'Location (optional)', class: 'col-3 col-form-label'
          .col-9
            = f.text_field :location, class: 'form-control'
        .form-group.row
          = f.label :description, 'Description (optional)', class: 'col-3 col-form-label'
          .col-9
            = f.text_area :description, class: 'form-control', placeholder: 'Describe Yourself', rows: '3'
        .form-group.row
          = f.label :work, "Occupation (optional)", class: 'col-3 col-form-label'
          .col-9
            = f.text_field :work, class: 'form-control', placeholder: 'Your job'
        .form-group.row
          .col-3 Topics Interested (optional)
          .col-9
            = f.collection_check_boxes(:topic_ids, Topic.all, :id, :name) do |cb|
              .form-check
                = cb.label(class: 'form-check-label') { cb.check_box(class: 'form-check-input') + cb.text}
        .form-group.row
          .col-3
          .col-9
            = f.submit "Submit", class: 'btn btn-primary'
            

app/views/users/show.html.haml
.container.p-3
  .row
    .col-8
      .row
        / details of the user
        .col-3
          %img.rounded-circle{:alt => "Your Photo", :src => "http://via.placeholder.com/150x150"}
        .col-9
          %h5= @user.name
          %p= @user.description
      %hr
      .row
        .col-3
          %ul
            %li
              %h6 Feeds
            %hr
              %li
                = link_to user_path(@user) do
                  Answers
                  %span.badge.badge-dark= @user.answers.size
              %li
                = link_to user_path(@user, tab: 'question') do
                  Questions
                  %span.badge.badge-dark= @user.questions.size
        .col-9
          - if params[:tab].nil?
            #{@user.answers.size} Answers
            %hr
              - @user.answers.each do |answer|
                .card.mb-2
                  .card-body
                    %p.card-text= answer.body
                    %p.card-text.txt-sm answered for the question #{link_to answer.question.body, question_path(answer.question), class: 'clickable'}
          - elsif params[:tab] == 'question'
            #{@user.questions.size} Questions
            %hr
              - @user.questions.each do |question|
                = render 'questions/question', question: question

    .col-4
      .row
        .col-12
          %h5 Credentials & Highlights
          %hr
            %ul
              - unless @user.work.blank?
                %li Works as #{@user.work}
              - else
                %li= link_to 'Add work details', edit_user_path
              - unless @user.location.blank?
                %li Lives in #{@user.location}
              - else
                %li= link_to 'Add location details', edit_user_path
        / end of row
      .row
        .col-12
          %h5 Knows About
          %hr
            %ul
              - @user.topics.each do |topic|
                %li= topic.name