config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#front'
  resources :pages, only: [:index]

  resources :questions, only: [:index, :show, :create, :destroy], param: :slug do
    resources :answers, only: [:create, :destroy] do
      member do
        post 'vote'
      end
    end
    collection do
      get 'interest'
    end
  end

  resources :searches, only: [:index]

  resources :users, only: [:create, :edit, :show, :update]

  get 'register', to: 'users#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  has_many :votes, dependent: :destroy

  validates :body, presence: { message: 'Answer cannot be blank' }

  default_scope { order('votes_count DESC') }

  def short_version
    words = body.split(' ')
    if words.size > 50
      words = words.take(50) << '...'
      return words.join(' ') 
    end
    body
  end

  def generate_vote_notification(current_user)
    message = "#{current_user.name} has upvoted your answer. (#{question.body})"
    self.user.notifications.create(message: message, question: question) unless self.user == current_user
  end

  def generate_answer_notification(current_user)
    message = "#{current_user.name} has answered your question. (#{question.body})"
    question.user.notifications.create(message: message, question: question) unless question.user == current_user
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :requires_sign_in
  before_action :requires_answer_owner, only: [:destroy]
  
  def create
    question = Question.find_by slug: params[:question_slug]
    additional_params = { 
      question_id: question.id,
      user: current_user
    }
    
    @answer = Answer.new(answer_params.merge(additional_params))

    if @answer.save
      flash[:success] = "Your answer successfully posted."
      @answer.generate_answer_notification(current_user)
      redirect_to question_path(params[:question_slug])
    else
      flash[:warning] = @answer.errors.messages[:body].first
      redirect_to question_path(params[:question_slug])
    end
  end

  def vote
    @answer = Answer.find(params[:id])
    @vote = @answer.votes.create(user: current_user, value: true)
    @answer.generate_vote_notification(current_user) if @vote.valid?

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @answer.destroy
    redirect_to question_path(params[:question_slug])
  end

  private

  def requires_answer_owner
    @answer = Answer.find(params[:id])
    unless current_user == @answer.user
      flash[:warning] = "Only can be deleted by answer owner."
      redirect_to question_path(params[:question_slug])
    end
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/views/answers/_answer.html.haml
%div
  %p
    #{answer.user.name}, #{answer.user.work} 
    %br/
    %span.text-muted.txt-sm Answered on #{format_date(answer.created_at)}
  %p.text-justify= answer.body
  = link_to vote_question_answer_path(@question, answer), method: 'post', remote: true, class: 'btn btn-outline-success btn-sm mr-2' do
    Upvote | <span id="answers_#{answer.id}_vote">#{answer.votes_count}</span>
  - if current_user == answer.user || current_user.admin?
    = link_to question_answer_path(@question, answer), method: 'delete', class: 'btn btn-outline-danger btn-sm' do 
      Delete
  - else
    = link_to question_answer_path(@question, answer), method: 'delete', class: 'btn btn-outline-danger btn-sm disabled' do 
      Delete    
  %hr/

app/views/answers/vote.js.haml
- if @vote.valid?
  $("#answers_#{@answer.id}_vote").html("#{@answer.votes.size}")