config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#front'
  resources :pages, only: [:index]

  resources :questions, only: [:index, :show, :create, :destroy], param: :slug do
    resources :answers, only: [:create, :destroy] do
      member do
        post 'vote'
      end
    end
    collection do
      get 'interest'
    end
  end

  resources :searches, only: [:index]

  resources :users, only: [:create, :edit, :show, :update]

  get 'register', to: 'users#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  
end

app/views/pages/front.html.haml
.jumbotron
  .container
    %h1.display-4 Hello, Guest
    %p.lead Welcome to Quora, ask any question and let the Internet answer them!

    %hr.my-4

    %p Please sign in to use the features. Register a free account otherwise !
    %p.lead
      = link_to 'Register', register_path, class: 'btn btn-secondary btn-lg'

app/views/pages/index.html.haml
.container.py-3
  .row
    .col-3
      %ul
        %li
          %h6 Feeds
        %hr/
        %li
          = link_to 'Most Popular Questions', pages_path(sort: 'top_views')
        %li
          = link_to 'Newest Questions', pages_path
    .col-7
      %h5 All Questions from Quora
      %hr
      - @questions.each do |question|
        = render 'questions/question', question: question
      .digg_pagination
        = will_paginate @questions, :page_links => true