config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#front'
  resources :pages, only: [:index]

  resources :questions, only: [:index, :show, :create, :destroy], param: :slug do
    resources :answers, only: [:create, :destroy] do
      member do
        post 'vote'
      end
    end
    collection do
      get 'interest'
    end
  end

  resources :searches, only: [:index]

  resources :users, only: [:create, :edit, :show, :update]

  get 'register', to: 'users#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg| 
  %div(class="alert alert-#{name} alert-dismissible fade show")
    = msg
    %button.close(type="button" data-dismiss="alert")
      %span &times;

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container
    = link_to 'Quora', root_path, class: 'navbar-brand mr-5'
    .collapse.navbar-collapse
      .navbar-nav.col-8
        - if logged_in?
          = link_to 'Home', questions_path, class: 'nav-link'
          = link_to 'Answer', interest_questions_path, class: 'nav-link'
          .dropdown
            %a#dropdownMenuButton.nav-link.notification.dropdown-toggle{"data-toggle" => "dropdown"}
              Notification
            .dropdown-menu.notify-box
              - if current_user.notifications.blank?
                %a.dropdown-item You have no new notification.
              - else
                - current_user.notifications.each do |notification|
                  = link_to notification.question, class: 'dropdown-item' do 
                    = notification.message
                  %div.dropdown-divider
        - else
          = link_to 'Home', questions_path, class: 'nav-link disabled'
          = link_to 'Answer', interest_questions_path, class: 'nav-link disabled'
          .dropdown
            %a#dropdownMenuButton.nav-link.notification.dropdown-toggle.disabled{"data-toggle" => "dropdown"}
              Notification

        = form_tag searches_path, method: 'get', class: 'form-inline col-8' do
          - if logged_in?
            = search_field :search_question, :body, {class: "form-control col-12", placeholder: 'Search question title'}
          - else
            = search_field :search_question, :body, {class: "form-control col-12", placeholder: 'Search question title', disabled: true}

        .btn-group
          - if logged_in?
            %button.btn.btn-outline-primary{:type => "button"}= current_user.name
            %button.btn.btn-outline-primary.mr-2.dropdown-toggle.dropdown-toggle-split{"data-toggle" => "dropdown", :type => "button"}
            .dropdown-menu
              = link_to 'Profile', user_path(current_user), class: 'dropdown-item'
              = link_to 'Settings', edit_user_path(current_user), class: 'dropdown-item'
              .dropdown-divider
              = link_to 'Logout', logout_path, class: 'dropdown-item'

            %a.nav-link.btn-outline-danger.btn.btn-sm{"data-target" => "#questionModal", "data-toggle" => "modal", :href => "#"} Add Question
            / Modal
            #questionModal.modal.fade{:tabindex => "-1"}
              .modal-dialog
                .modal-content
                  .modal-header
                    %h5.modal-title Please Ask Your Question
                    %button.close{"data-dismiss" => "modal", :type => "button"}
                      %span ×
                  .modal-body
                    = form_for @new_question do |f|
                      .form-group
                        = f.text_field :body, class: 'form-control no-border-text', placeholder: "Type question here."
                      .form-group
                        = f.text_field :topics, class: 'form-control form-control-sm', placeholder: 'AI, computer science, literature', value: ''
                      .modal-footer
                        %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
                        = f.submit 'Add Question', class: 'btn btn-primary'
          - else
            %button.btn.btn-outline-primary{:type => "button"} Log In
            %button.btn.btn-outline-primary.mr-2.dropdown-toggle.dropdown-toggle-split{"data-toggle" => "dropdown", :type => "button"}
            .dropdown-menu.login-menu
              = form_tag '/login', method: 'post', class: 'px-4 py-3' do
                .form-group
                  = label_tag 'email', 'Email address'
                  = email_field_tag 'email', nil, class: 'form-control', placeholder: 'email@example.com'
                .form-group
                  = label_tag 'password', 'Password'
                  = password_field_tag 'password', nil, class: 'form-control', placeholder: 'enter password'
                = submit_tag "Sign in", class: 'btn btn-primary'
              .dropdown-divider
              = link_to 'New around here? Sign up', '/register', class: 'dropdown-item'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title Quora Q&A Site
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tag
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
  %body
    %header
      = render 'layouts/navigation'
    %main
      %div
        = render 'layouts/messages'
      = yield